### PR TITLE
Repository query execution refactored (ArangoAqlQuery)

### PR DESCRIPTION
**Pull request by christian-lechner**
Hi!

I saw that the `ArangoAqlQuery#execute` method contains nearly the complete logic for repository query methods. This method is executed everytime when a repository query method is called. Two points that are not optimal in this method:
- operations where the result never changes is computed on every call (e.g. check for duplicate bind parameter names)
- hard to maintain spaghetti code

**CHANGELOG:**
- `@Param` annotation deprecated, there is already such an annotation from Spring Data (the code in this PR supports both and can be removed once the old annotation is removed)
- Splitted `ArangoAqlQuery` into three parts: `AbstractArangoQuery` (common code), `StringBasedArangoQuery` (for methods with `@Query` annotation or named queries) and `DerivedArangoQuery` (queries generated from method name)
- Moved functionality into better fitting classes: 
  - `ArangoParameter`: operations on parameter level, e.g. check if param is `AqlQueryOptions` or has `@BindVars` annotation
  - `ArangoParameters`: parameters of a method, e.g. check for non duplicate param names
  - `ArangoParametersParameterAccessor`: combination of parameters of a method and the actual values, e.g. getters for special values (`AqlQueryOptions`, ...).
  - `ArangoQueryMethod`: operations on the method itself, e.g. get query string from `@Query` annotation
- Added support for named queries
- Added `ArangoEntityInformation` in `ArangoRepositoryFactory`

Most of the classes had no author credits so I added them by checking `git blame`. I hope that's ok - I tried my best to credit the original authors. More attention should be paid to this in the future.

This PR is not finished yet. The tests must be adjusted, because the checks are now performed when the repository is created and Spring Data doesn't even start when an assertion is violated (e.g. duplicate param names).

### CODE REVIEW

**Comment by christian-lechner** [comment]
I discovered a locale dependent bug in the `DerivedQueryCreator`. It uses `String.format` to format Strings, which uses the system default locale. But when formatting floating point numbers with `%f`, there are locales that use `,` as the decimal point instead of `.`. As a result the query is syntactically wrong and ArangoDB throws a parse exception.

I will include a fix that sets the locale to `Locale.ENGLISH`.

**Comment by christian-lechner** [comment]
@mpv1989 you make use of the `ArangoConverter#isEntityType(type)` method in `ArangoExtCursorIterator`. `isEntityType` uses `CustomConversions.isSimpleType(type)` internally. The problem is that this method also returns `true` for types that have a **writing** converter registered to a real simple type (e.g. `Customer` -> `String`, then `Customer` would be a simple type).

`ArangoConverter#isEntityType(type)` decides if the `ArangoConverter` or the deserializer of the Java driver is used. So if I create a custom **writing** converter from `Customer` -> `String` and I want to read customers from the DB the Java driver deserializer is used. Two things are wrong here:
- the `ArangoConverter` should be used
- the conversion would still fail, because we don't have a reading converter (we don't have registered one and `CustomConversions.isSimpleType(type)` only checks for writing converters

The `CustomConversions.isSimpleType(type)` should only be used internally by the `ArangoConverter` to check if we have custom write targets and not read targets.

I think we should use the `ArangoSimpleTypes.HOLDER.isSimpleType(type)` instead which really contains the simple types that can be handled by the Java driver directly.

**Comment by mpv1989** [comment]
@christian-lechner totally agree. We should change this.

**Comment by christian-lechner** [comment]
@mpv1989 I added a few other changes:
- made `ArangoTemplate#version` volatile that not every thread must possibly request the version again
- added more simple types (primitive arrays, `BaseDocument`, `BaseEdgeDocument`, `VPackSlice`)
- moved `DESERIALIZABLE_TYPES` to `ArangoExtCursorIterator` (that they are also applied when `ArangoOperations#query` is called) and removed duplicate types (compared to Arango Simple Types)

I think this PR is quite complete now. @mpv1989 please have a look if you find some time ;)

**Comment by mpv1989** [comment]
@christian-lechner looks very good.

I am just thinking about what of your changes all belongs in the documentation. I think for users are actually only the named queries relevant. What do you think?

**Comment by christian-lechner** [comment]
I rebased the commits in this PR to get rid of an already merged and "merge branch master" commit.

@mpv1989 yes the named queries functionality is the only new thing. I will add a few lines to the docs.

**Comment by christian-lechner** [comment]
@mpv1989 the current docs state the following:

> AQL supports the usage of [bind parameters](https://docs.arangodb.com/3.1/AQL/Fundamentals/BindParameters.html) which you can define with a method **parameter named `bindVars`** of type `Map<String, Object>`.

The bold part is not correct. There must be a `@BindVars` annotation. Should I update this part?

**Comment by mpv1989** [comment]
@christian-lechner yes, please.

**Comment by christian-lechner** [comment]
Named queries section added to doc.

**Comment by mpv1989** [comment]
Very nice. I think the PR is now ready to merge or anything from your side left?

**Comment by christian-lechner** [comment]
I think it's complete. You can pull the trigger :rofl:

**Comment by mpv1989** [comment]
🎉 Thanks again

**Pull request merged**
