### PR TITLE
This is an optimization to PR #33 & resolves https://github.com/arangodb/spring-data/issues/40

### PR DESCRIPTION
**Pull request by haqer1**
There's an automated test case of the optimization that is coded to pass only if the efficient, clean & logical approach for a mainstream inheritance type like COLLECTION/TABLE PER CLASS (originally submitted under PR #18) is used: this is better from disk space, memory, bandwidth, & CPU points of view (not to mention avoiding the clutter when looking at the data (which is actually also a big factor, once i've taken a look at it)).

### CODE REVIEW

**Comment by haqer1** [comment]
Because PRs went out of order (& out of logic IMHO), i've ended up not only developing what i needed:
1. Core fix/enhancement for COLLECTION/TABLE_PER_CLASS type inheritance support for associations
but also
2. COLLECTION/TABLE_PER_CLASS type inheritance support for collections-based associations (for which i don't have a need yet)
and
3. Optimizing PR #33, in which i had no interest at all.

This has taken too long. I hope this is merged quickly, so that i don't have to spend any more time on this (& so that i don't have to keep my own fork of arangodb-spring-data for as long as i use it).

**Comment by haqer1** [comment]
> i've ended up not only developing what i needed:
    Core fix/enhancement for COLLECTION/TABLE_PER_CLASS type inheritance support for associations
    but also
    COLLECTION/TABLE_PER_CLASS type inheritance support for collections-based associations (for which i don't have a need yet)
    and
    Optimizing PR #33, in which i had no interest at all.
...  I hope this is merged quickly, so that i don't have to spend any more time on this (& so that i don't have to keep my own fork of arangodb-spring-data for as long as i use it).

For the record, since a conflict was introduced by a commit in upstream last week, i've had to spend some more time on merging manually 1 more time (now there are no conflicts).

**Comment by haqer1** [comment]
>  i've ended up not only developing what i needed:
    1. Core fix/enhancement for COLLECTION/TABLE_PER_CLASS type inheritance support for associations
    but also
    2. COLLECTION/TABLE_PER_CLASS type inheritance support for collections-based associations (for which i don't have a need yet)
    and
    3. Optimizing PR 33, in which i had no interest at all.
    ... I hope this is merged quickly, so that i don't have to spend any more time on this (& so that i don't have to keep my own fork of arangodb-spring-data for as long as i use it).
For the record, since a conflict was introduced by a commit in upstream last week, i've had to spend some more time on:
4. Merging manually 1 more time (now there are no conflicts).

For the record, since another conflict was introduced by a commit in upstream last week, i've had to spend some more time on:
5. Merging manually yet another time (now there are no conflicts again).

P.S. @MrPieces: this PR only optimizes inefficiencies in PR 33 related to COLLECTION-per-CLASS type of inheritance support (which had originally been implemented rationally by PR 18) (other stuff (including bizarre inheritance-related approaches to associations that nobody would use in real-world) is unaffected by it).

**Comment by christian-lechner** [comment]
This PR does not optimize anything, but sabotages the type mapping process.

**Comment by haqer1** [comment]
> This PR does not optimize anything

Given that you've already read comments like https://github.com/arangodb/spring-data/pull/18#issuecomment-390607209 (since you've responded), you are lying.
Until the shady business is taken care of, because PRs 18 & 41 have been sabotaged by 2 people, ArangoDB will be characterized by the following previously-mentioned issues (which this PRs 18 & 41 would have optimized/resolved):
https://github.com/haqer1/arangodb-spring-data-rational#inefficiencies_optimized

I have no doubt that at some point in time, fully-qualified class names will no longer be stored in ArangoDB to support main-stream persistence types such as COLLECTION-PER-CLASS. Some time, due to a reasonable request or just by making some kind of excuse (of which a lot has been seen here lately), a reasonable implementation such as that provided by PRs 18 & 41 will be provided. And intellect and/or integrity of all the people who have watched the absurd in ArangoDB spring-data between April 17, 2018 & that future time will be in question.

So the question @MrPieces, ArangoDB's senior management, owners, venture capital providers, etc. might be well advised to ask themselves is: since the decisions made regarding PRs 18 & 41 clearly & without any doubt are not driven by reasoning related to technological characteristics (such as performance (disk, memory, bandwidth, CPU), ease of use, developer-friendliness, admin-friendliness, etc., & that even additional costs being caused by not merging PRs 18 & 41 have been ignored), what has been behind these decisions? With time, this will become evident: it's only a matter of how much time will be necessary.

**Pull request closed without merging**
