### PR TITLE
Converter now handles array elements (#147)

### PR DESCRIPTION
**Pull request by nickcodefresh**
Fixes https://github.com/arangodb/spring-data/issues/147

### CODE REVIEW

**Comment by rashtao** [comment]
@nickcodefresh the PR does not pass the tests, since collections are now not correctly mapped!

**Comment by nickcodefresh** [comment]
how do I run the tests? Running `mvn test` gives me lots of "connection refused" errors,

**Comment by rashtao** [comment]
Fixed in https://github.com/arangodb/spring-data/pull/160

**Comment by rashtao** [comment]
@nickcodefresh can you confirm that https://github.com/arangodb/spring-data/pull/160 fixes it?

**Pull request closed without merging**
