### PR TITLE
[Bug][Lombok] canEqual

### PR DESCRIPTION
**Pull request by PauloFerreira25**
Hello gentlemen.

I found a small bug, regarding lombok.

When using some native Java compare function on a list that is using @Ref for a document that is using lombok, Java tries to access the canEqual method.

But lombok puts this method as protected and AbstractResolver cannot call this method.

There is already a form of prevention in AbstractResolver for this scenario, but for other methods. I made the inclusion for this method.

The lombok documentation:
<https://projectlombok.org/features/EqualsAndHashCode>

Thank you for your attention

### CODE REVIEW

**Comment by rashtao** [comment]
Thanks for contributing! In order to avoid future regressions, can you please also add a test?

**Comment by PauloFerreira25** [comment]
Hi,

I believe I managed to create a test that simulates the behavior that lombok itself creates without including the lombok lib in the project.

I don't know how to make a test that "forces the error". But if you remove the da line to see the problem happening.
```java
if (method.getName().equals("canEqual")) {
return proxyCanEqual(ensureResolved(), args[0]);
}
```

Thank you for your attention

**Comment by rashtao** [comment]
Actually lombok is a test dependency, so you should be able to use lombok annotations in tests, eg. see https://github.com/arangodb/spring-data/blob/d0d0ada88d133ce3de3aebc467da087b2364106a/src/test/java/com/arangodb/springframework/debug/repository/entity/User.java

**Review by PauloFerreira25 — COMMENTED** [review]
Done

**Comment by PauloFerreira25** [comment]
Hello, I did the conversion to use native lombok.

I agree that it is better to use lombok than to do it manually.

Thank you for your attention

**Pull request merged**
